import React, { useState } from 'react';
import DashboardSidebar from '@/components/DashboardSidebar';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Download, BookOpen, FileText, ExternalLink, CheckCircle, Search } from 'lucide-react';
import { Input } from '@/components/ui/input';
import jsPDF from 'jspdf';
import { toast } from 'sonner';
import { Link } from 'react-router-dom';

import { syllabusData, type SubjectSyllabus, type SyllabusTopic } from '@/data/jambSyllabus';


const JambSyllabus: React.FC = () => {
  const [selectedSubject, setSelectedSubject] = useState<SubjectSyllabus | null>(null);
  const [searchTerm, setSearchTerm] = useState('');

  const filteredSubjects = syllabusData.filter(subject =>
    subject.name.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const downloadSyllabusPDF = (subject: SubjectSyllabus) => {
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      let yPosition = 20;
      const lineHeight = 7;
      const margin = 20;
      const maxWidth = pageWidth - margin * 2;

      // Title
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text(`JAMB ${subject.name} Syllabus`, pageWidth / 2, yPosition, { align: 'center' });
      yPosition += 15;

      // Subtitle
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text('Official Syllabus for UTME Examination', pageWidth / 2, yPosition, { align: 'center' });
      yPosition += 5;
      doc.text('Source: Joint Admissions and Matriculation Board (JAMB)', pageWidth / 2, yPosition, { align: 'center' });
      yPosition += 15;

      // Topics
      subject.topics.forEach((topic, topicIndex) => {
        // Check if we need a new page
        if (yPosition > 260) {
          doc.addPage();
          yPosition = 20;
        }

        // Topic header
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text(`${topicIndex + 1}. ${topic.topic}`, margin, yPosition);
        yPosition += lineHeight + 2;

        // Subtopics
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        topic.subtopics.forEach((subtopic, subIndex) => {
          if (yPosition > 270) {
            doc.addPage();
            yPosition = 20;
          }
          const lines = doc.splitTextToSize(`• ${subtopic}`, maxWidth - 10);
          lines.forEach((line: string) => {
            doc.text(line, margin + 5, yPosition);
            yPosition += lineHeight;
          });
        });
        yPosition += 5;
      });

      // Footer
      doc.setFontSize(8);
      doc.setFont('helvetica', 'italic');
      doc.text('Generated by Spark Study - www.sparkstudy.com', pageWidth / 2, 285, { align: 'center' });

      // Save the PDF
      doc.save(`JAMB_${subject.name}_Syllabus.pdf`);
      toast.success(`${subject.name} syllabus downloaded successfully!`);
    } catch (error) {
      console.error('Error generating PDF:', error);
      toast.error('Failed to generate PDF. Please try again.');
    }
  };

  return (
    <div className="flex h-screen bg-background">
      <DashboardSidebar />
      <div className="flex-1 overflow-auto pt-16 md:pt-0">
        <div className="py-4 px-4 md:py-6 md:px-8">
          <div className="mb-6">
            <h1 className="text-xl md:text-2xl font-bold flex items-center gap-2 text-foreground">
              <BookOpen className="h-6 w-6 text-primary" />
              2025 JAMB Syllabus
            </h1>
            <p className="text-sm text-muted-foreground">
              The full 2025 UTME syllabus for every subject — view, download, and practise questions on the exact topics you are examined on
            </p>

          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Subject List */}
            <div className="lg:col-span-1">
              <Card className="bg-card">
                <CardHeader>
                  <CardTitle className="text-lg text-foreground">Select Subject</CardTitle>
                  <div className="relative">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                    <Input
                      placeholder="Search subjects..."
                      value={searchTerm}
                      onChange={(e) => setSearchTerm(e.target.value)}
                      className="pl-9"
                    />
                  </div>
                </CardHeader>
                <CardContent>
                  <ScrollArea className="h-[400px] pr-4">
                    <div className="space-y-2">
                      {filteredSubjects.map((subject) => (
                        <button
                          key={subject.name}
                          onClick={() => setSelectedSubject(subject)}
                          className={`w-full text-left p-3 rounded-lg transition-all flex items-center justify-between ${
                            selectedSubject?.name === subject.name
                              ? 'bg-primary text-primary-foreground'
                              : 'bg-muted hover:bg-muted/80 text-foreground'
                          }`}
                        >
                          <span className="font-medium">{subject.name}</span>
                          {selectedSubject?.name === subject.name && (
                            <CheckCircle className="h-4 w-4" />
                          )}
                        </button>
                      ))}
                    </div>
                  </ScrollArea>
                </CardContent>
              </Card>
            </div>

            {/* Syllabus Content */}
            <div className="lg:col-span-2">
              {selectedSubject ? (
                <Card className="bg-card">
                  <CardHeader>
                    <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
                      <div>
                        <CardTitle className="text-xl text-foreground">{selectedSubject.name} Syllabus (2025)</CardTitle>
                        <CardDescription>
                          {selectedSubject.topics.length} examinable topics for JAMB {selectedSubject.name}
                        </CardDescription>
                      </div>
                      <Button variant="outline" onClick={() => downloadSyllabusPDF(selectedSubject)}>
                          <Download className="h-4 w-4 mr-2" />
                          Download PDF
                      </Button>
                    </div>
                    <div className="flex flex-wrap gap-2 pt-2">
                      <Button size="sm" asChild>
                        <Link to={`/dashboard/past-questions?subject=${encodeURIComponent(selectedSubject.name)}`}>
                          Practise {selectedSubject.name} questions
                        </Link>
                      </Button>
                      <Button size="sm" variant="secondary" asChild>
                        <Link to={`/dashboard/cbt-exam?subject=${encodeURIComponent(selectedSubject.name)}`}>
                          Take a CBT mock
                        </Link>
                      </Button>
                    </div>
                  </CardHeader>

                  <CardContent>
                    <Accordion type="multiple" className="w-full">
                      {selectedSubject.topics.map((topic, index) => (
                        <AccordionItem key={index} value={`topic-${index}`}>
                          <AccordionTrigger className="hover:no-underline">
                            <div className="flex items-center gap-2">
                              <Badge variant="secondary" className="mr-2">
                                {index + 1}
                              </Badge>
                              <span className="font-medium text-foreground">{topic.topic}</span>
                            </div>
                          </AccordionTrigger>
                          <AccordionContent>
                            <ul className="space-y-2 pl-8">
                              {topic.subtopics.map((subtopic, subIndex) => (
                                <li key={subIndex} className="flex items-start gap-2 text-muted-foreground">
                                  <CheckCircle className="h-4 w-4 text-green-500 mt-0.5 shrink-0" />
                                  <span>{subtopic}</span>
                                </li>
                              ))}
                            </ul>
                          </AccordionContent>
                        </AccordionItem>
                      ))}
                    </Accordion>

                    <div className="mt-6 p-4 bg-primary/10 rounded-lg">
                      <p className="text-sm text-foreground">
                        <span className="font-medium">Note:</span> This syllabus is based on the official JAMB syllabus. 
                        For the most up-to-date version, please download the official PDF from JAMB.
                      </p>
                      <Button variant="link" className="p-0 h-auto mt-2" asChild>
                        <a href="https://www.jamb.gov.ng" target="_blank" rel="noopener noreferrer">
                          Visit JAMB Official Website <ExternalLink className="h-3 w-3 ml-1" />
                        </a>
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              ) : (
                <Card className="text-center py-12 bg-card">
                  <CardContent>
                    <FileText className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
                    <h3 className="text-lg font-semibold mb-2 text-foreground">Select a Subject</h3>
                    <p className="text-muted-foreground">
                      Choose a subject from the list to view its JAMB syllabus
                    </p>
                  </CardContent>
                </Card>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default JambSyllabus;
